name: balanco_app
description: Aplicativo de balanço de estoque.
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.3
  mask_text_input_formatter: ^1.1.0
  string_mask: ^0.1.0
  sqflite: ^1.3.2+3
  flutter_barcode_scanner: ^1.0.1
  path_provider: ^1.6.27
  http: ^0.12.2
  dio: ^3.0.10
  animated_splash_screen: ^1.0.1+2
  connectivity_plus: any
  cupertino_icons: ^1.0.0
  string_validator: ^0.1.4
  jwt_decoder: ^1.0.3
  json_string: ^2.0.1
  flutter_launcher_icons: ^0.7.5
  http_client: ^1.4.2
  animated_text_kit: ^3.1.0
  dynamic_color_theme: any
  animated_card: ^1.0.0+8
  sizer: ^1.1.8
  flutter_easyloading: ^2.2.2
  #foreground_service: ^2.0.1+1
  flutter_foreground_plugin: ^0.6.0
  liquid_progress_indicator: ^0.3.2
  safe_url_check: ^1.0.0
  wifi_iot: ^0.2.2



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons :
  caminho : ../

flutter_icons :
  image_path_android : "assets/images/logotipo.png"
  image_path_ios : "assets/images/logotipo.png"
  android : true
  ios : true

flutter:
  uses-material-design: true
  assets:
    - assets/images/logotipo.png
    - assets/images/logotipo-fundo-branco.png
    - assets/images/logotipo_small.png


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
